# Kong Database
version: '2'
services:

  # Kong

  kong:
    image: kong:latest
    restart: always
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    ports:
      - 8000
      - 8443
      - 8001
    expose:
      - 7946
      - 7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
