version: '2'

services:
  kong-database:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
volumes:
  postgres-db-volume:
    driver: local
