# Kong Database
version: '2'
services:


  kong:
    build: kong/
    restart: always
    ports:
      - 8000
      - 8443
      - 8001
    expose:
      - 7946
      - 7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${DATABASE}
